### ISSUE TITLE
StackNavigator shared element transition between activities

### ISSUE THREAD

**Issue by wman1980** [tunjid/Android-Extensions#106]
Hi @tunjid,

actually I discovered an issue while implementing shared element transitions between activities by using StackNavigator.
The issue is that the back transition of the shared element transition is not working because every fragment is added to the back stack. Every means that also the initial one is added to the back stack.

The issues lies within
`StackNavigator.push(fragment:Fragment, tag:String)`

to be more precise

```
fragmentManager.commit {
            transactionModifier?.invoke(this, fragment)
            replace(containerId, fragmentToShow, tag)
            addToBackStack(tag.toEntry)
        }
```

Is there a way to circumvent "addToBackStack(tag.toEntry)? 

If I do not use StackNavigator and simple use a transaction where I do not add the initial fragment to the back stack then the back transition of the shared element transition is working fine.

Do you need an example project?

Regards
wMan

**Comment by wman1980** [comment]
btw: its working if I use a MultiStackNavigator with stackCount = 1

**Comment by tunjid** [comment]
@wman1980 do you mean shared element transitions between `Fragment` or `Activity` instances? I'm not sure how a fragment manager would affect shared element transitions between activities, an example project would be much appreciated.

The sample app in this repo uses shared elements a lists tab with the doggo samples, they work okay for both going forward and back. The issue you may be running into is that when fragments are in the back stack, their view is destroyed, so your shared element name might not be consistent between the old and new fragments.

**Comment by wman1980** [comment]
I mean shared element transition between activities and each activity has a fragmentContainerView
