### ISSUE TITLE
BackStackType Unlimited/Restricted in version 1.2.1 not working correctly

### ISSUE THREAD

**Issue by wman1980** [tunjid/Android-Extensions#120]
Hi @tunjid,

I just checked out version 1.2.1. Thanks for the changes.

I discovered that something is not working correctly with BackstackType Unlimited or Restricted. Its working fine with uniqueEntries. I ONLY changed the type to Unlimited/Restricted.

Back press navigation within a tab with several fragments seems to work fine as well as switching then to the previous tab, but if the next previous tab just has only a root fragment I have to press twice the back button. 

It seems that it only occurs if I just navigate back between tabs with only root fragment added to it.

**Comment by tunjid** [comment]
@wman1980 hi! Can you give me exact steps to reproduce using the sample app in this repository?

Please use the names of the fragment you navigated to, the result you expected and then the result you got.

**Comment by wman1980** [comment]
hm ... its working fine with your example project.
will have a look at my setup. sorry for inconvenience

**Comment by tunjid** [comment]
@wman1980 did you resolve it? I want to close this issue.

**Comment by wman1980** [comment]
Did not have time to look into it.
Close it. I'll have a look and will come back to you if its related to your library
