### ISSUE TITLE
Example of Instagram-Like Navigation

### ISSUE THREAD

**Issue by Minification** [tunjid/Android-Extensions#13]
Hi,

would it be possible to add the Instagram-like navigation example from https://proandroiddev.com/simplifying-the-fragmentmanager-api-multiple-fragment-backstacks-on-android-9b64ddb0d654  also seen in the following gif

https://miro.medium.com/max/648/1*Rj7f7D3XfwUuXFlBnBSQ1A.gif

to the sample app?

I'm asking because I need exactly that but I don't really understand how to transfer the knowledge from the sample app to my app, where I pretty much need exactly what one can see in the gif.

In particular, I'm wondering how the fragments in the main activity are created since the root function in the sample app appears to create a new fragment each time it is called. Also, I was wondering how the inner fragments should be added in such a way that their state is preserved.

Please let me know if you need more information since the explanation I gave here is rather brief.

**Comment by tunjid** [comment]
@Minification 
The root function is called only once; when the tab is visited for the the first time. After that, tapping on a previously visited tab will just show the fragment returned by the root function previously.

```kotlin
    override val navigator: MultiStackNavigator by multiStackNavigationController(
            tabs.size,
            R.id.content_container,
            RouteFragment.Companion::newInstance // Will be called once for each index
    )
```

As far as inner fragments go, their state will be preserved automatically as the `FragmentManager` takes care of it. If you wanted to show a different fragment at the root of each index, like with Instagram, you could do

```kotlin
    override val navigator: MultiStackNavigator by multiStackNavigationController(
            4,
            R.id.content_container,
            { index -> 
                when(index){
                0 -> HomeFragment()
                1 -> ExploreFragment()
                2 -> ActivityFragment()
                3 -> ProfileFragment()
            }
    )
```

Within each inner fragment, if you wanted to go deeper into the tab, you can just get an instance of the navigator and `push` the new fragment like so:

```kotlin
class HomeFragment {
        private val navigator by activityNavigatorController<MultiStackNavigator>()

    fun goToPost(post: Post) {
        navigator.push(PostFragment.newInstance(post)
    }
}

**Comment by Minification** [comment]
Hi,

thanks for you quick reply, I think I understood.

I'm not sure if there isn't a bug, though. Assume we are using the example you gave above and `HomeFragment` has a button which takes us to `InnerHomeFragment`. Now I perform the following actions:

1. Start app, i.e. `HomeFragment`
2. `ExploreFragment`
3. `ActivityFragment`
4. `HomeFragment`
5. Press button, i.e. go to `InnerHomeFragment`
6. `ExploreFragment`
7. `ActivityFragment`

And now we press the back button a few times. What happens is the following:

1. `ExploreFragment`
2. `InnerHomeFragment`
3. `HomeFragment`
4. App shuts down gracefully (i.e. without errors)

Instead of the last step, I would have expected `ActivityFragment`, then `ExploreFragment`, then `HomeFragment `to show and then the app to shut down gracefully upon another back button press.

Is this inteded behaviour?

**Comment by tunjid** [comment]
@Minification Ah is see what you mean. The implementation of this is in `MultiStackVisitor` in `MultiStackNavigator.kt`; the assumption was no tab can exist twice in the nav history which is exactly what Instagram does. This can be modified, but like in the post you referenced, "Instagram-like navigation" is what I was going for with this.

**Comment by Minification** [comment]
I see, I believe instagram mostly circumvents this by swipes and button clicks navigating to fragments/activities without a bottom navigation view.

Would it be possible to make the `MultiStackVisitor` a overridable component of `MultiStackNavigator`, such that one could implement other behaviours?

**Comment by tunjid** [comment]
@Minification that can be done, but probably not till this weekend or the next. You can submit a PR for it with tests if you want, all you need to do is selectively call this line with some boolean flag and it should work: https://github.com/tunjid/Android-Extensions/blob/develop/navigation/src/main/java/com/tunjid/androidx/navigation/MultiStackNavigator.kt#L251

**Comment by tunjid** [comment]
@Minification done in https://github.com/tunjid/Android-Extensions/issues/102
