### ISSUE TITLE
How to add multiple viewholders in recyclerview?

### ISSUE THREAD

**Issue by chnouman** [tunjid/Android-Extensions#6]

**Comment by tunjid** [comment]
In what context? In general or with the library?

**Comment by chnouman** [comment]
@tunjid like in ComposedAdapter we have only one viewHolderCreater and only one viewHolderBinder. Somehow I want to send multiple view holders and view holder Binders. I tried adding one more view holder and binder separately in separate parameters but getting error. Below is some images of what I have done and where I stuck.
<img width="883" alt="error without label" src="https://user-images.githubusercontent.com/15146352/74098073-91d18a00-4b35-11ea-87a0-a6540221997e.PNG">

This is one I hover on the error: 
<img width="960" alt="error" src="https://user-images.githubusercontent.com/15146352/74098078-a0b83c80-4b35-11ea-81ee-8d89be1e5b6b.png">


Here is my implementation or changes in adapterOf method and composedAdapter: 

<img width="718" alt="implementation" src="https://user-images.githubusercontent.com/15146352/74098083-b6c5fd00-4b35-11ea-86c8-730950ce47b3.PNG">

**Comment by tunjid** [comment]
Oh I see. To create multiple `viewHolders`, you need to implement the `viewType` function. That function takes the item in the list as a parameter, so you can do a `when` there, and return different numbers for different view types.

Then in the `viewHolderCreator` you can do an `if/else` or `when` and return different `ViewHolders` based on the view type yo specified earlier.

**Comment by chnouman** [comment]
@tunjid amazing clean way to handle the problem. I was doing an entirely different things.
