### ISSUE TITLE
Kotlin-gradle-publin declared twice with different versions

### ISSUE THREAD

**Issue by denebchorny** [tunjid/Android-Extensions#8]
In this file, you had declared two times the kotlin-gradle-plugin.
https://github.com/tunjid/Android-Extensions/blob/develop/build.gradle

classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

This typo is nothing. But, Your code is fantastic. I am following step by step to grab some good practices. Then, I saw these two lines that distracted me a little

**Comment by tunjid** [comment]
👍 Thanks for pointing that out, will fix it.
