### ISSUE TITLE
How to use MaterialFadeThrough Transition as StackTransactionModifier?

### ISSUE THREAD

**Issue by wman1980** [tunjid/Android-Extensions#82]
Hi,

very nice library!

Currently I am asking myself how to implement MaterialFadeThrough-Transition during a stack-change?

I was able to implement a Cross-Fade Transition by using stackTransactionModifier of MultiStackNavigator like this
`
this.stackTransactionModifier = {
       setCustomAnimations(
    R.anim.fade_in,
    R.anim.fade_out,
    R.anim.fade_in,
    R.anim.fade_out
)
    }
`

But how to do this by using a MaterialFadeThrough Transition?

**Comment by tunjid** [comment]
Hi @wman1980, thanks for checking out the library. `MainActivity` has an example of this using an extension:

`navigator.stackTransactionModifier = navigator.materialFadeThroughTransition()`

The full implementation is:

```kotlin
fun MultiStackNavigator.materialFadeThroughTransition(): FragmentTransaction.(Int) -> Unit = fade@{ index ->
    val rootFragmentManager = current?.activity?.supportFragmentManager ?: return@fade

    rootFragmentManager.findFragmentByTag(activeIndex.toString())?.apply {
        enterTransition = null
        if (exitTransition !is MaterialFadeThrough) exitTransition = MaterialFadeThrough().setDuration(300)
    }
    rootFragmentManager.findFragmentByTag(index.toString())?.apply {
        exitTransition = null
        if (enterTransition !is MaterialFadeThrough) enterTransition = MaterialFadeThrough().setDuration(300)
    }
}
```

**Comment by wman1980** [comment]
ahh, that is awesome!

I just forgot about the supportFragmentManager and the index.

Thanks a lot!

**Comment by wman1980** [comment]
Hi @tunjid,

I have a follow up question.

If I add some Transition.TransitionListener to that code above to to listen to start and end events for each transition. Do you have an idea how I could pass these events to my active fragment or target fragment?

Thanks

**Comment by tunjid** [comment]
@wman1980 `MultistackNavigator.current` and `MultistackNavigator.previous` should give you you a reference to your `Fragment` in your `Transtion.Listener`. Do you have a snippet of what you're trying to achieve with the listener?

**Comment by wman1980** [comment]
Actually I have a WebView within android and the webview "flickers/blinks" if a transition (MaterialSharedAxis.X) is started. My plan to prevent that was to create a bitmap snapshot and put that snapshot in front of the webview on transition start and remove that snapshot on transition end. But unfortunately I just discovered that onDestroyView of my fragment is called before onTransitionStart e.g. during a returnTransition.
